sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t sm/docker-react-app -f Dockerfile.dev /

script:
  - docker run -e CI=true sm/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-727075781018"
  bucket_path: "docker-react-app"
  on:
    branch: master
  
  access_key_id : $AWS_Access_Key
  secret_access_key : $AWS_Secret_Access_Key