sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t sm/docker-react-app -f Dockerfile.dev /

script:
  - docker run -e CI=true sm/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"